function (generate_executable)
    foreach(filename IN LISTS ARGN)
        string(REPLACE ".cpp" "" targetname ${filename})
        add_executable(${targetname} ${filename})
        target_link_libraries(${targetname} scopi)
    endforeach()
endfunction()
